---
id: asyncio并发
title: 本文内容
sidebar_label: asyncio并发
---



## 多线程协作

```
import itertools
import sys
import threading
import time


class Signal:
    go = True


def spin(msg, signal):
    write, flush = sys.stdout.write, sys.stdout.flush
    status = ''
    for char in itertools.cycle('|/-\\'):
        status = char + ' ' + msg
        write(status)
        flush()
        write('\x08' * len(status))  # 退格以清除掉之前的输出
        time.sleep(.1)
        if not signal.go:
            break
    write(' ' * len(status) + '\x08' * len(status))


def slow_function():
    # 假装等待I/O一段时间
    time.sleep(3)
    return 42


def supervisor():
    signal = Signal()
    spinner = threading.Thread(target=spin, args=('thinking!', signal))
    print('spinner object:', spinner)
    spinner.start()
    result = slow_function()
    signal.go = False
    spinner.join()
    return result


def main():
    result = supervisor()
    print('Answer:', result)


if __name__ == '__main__':
    main()

```

- 一个线程负责输出，一个线程负责计算
- 计算线程获取到结果后，直接修改共享内存变量，来通知另一个线程
- 终端输出的动画效果是依靠输出退格符 \x08 来实现的
- itertools 用来输出无限迭代，他会循环迭代集合里的内容



## asyncio 包的版本

```
import asyncio
import itertools
import sys


@asyncio.coroutine
def spin(msg):
    write, flush = sys.stdout.write, sys.stdout.flush
    status = ''
    for char in itertools.cycle('|/-\\'):
        status = char + ' ' + msg
        write(status)
        flush()
        write('\x08' * len(status))
        try:
            yield from asyncio.sleep(.1)  # 睡 0.1 秒，实际来说是将线程的控制权交出去，线程还是会继续执行其它的代码（协程）
        except asyncio.CancelledError:
            break  # 这里表示被其它协程将自己这个协程给取消了，相当于一种通知机制
    write(' ' * len(status) + '\x08' * len(status))


@asyncio.coroutine
def slow_function():
    # 假装等待I/O一段时间
    yield from asyncio.sleep(3)  # 这个协程休眠 3 秒钟，同样的，执行这个协程的线程去执行其它协程了
    return 42


@asyncio.coroutine
def supervisor():
    spinner = asyncio.ensure_future(spin('thinking!'))  # 将这个协程丢进 event loop，然后返回一个 future
    print('spinner object:', spinner)
    result = yield from slow_function()  # 本协程将控制权交出去，交给这个 slow function
    spinner.cancel()  # 运行到这里的时候，spin 已经运行过一段时间了
    return result


def main():
    loop = asyncio.get_event_loop()
    result = loop.run_until_complete(supervisor())
    loop.close()
    print('Answer:', result)


if __name__ == '__main__':
    main()

```

### 说明

- `asyncio `是Python 3.4版本引入的标准库，直接内置了对异步IO的支持
- 它的编程模型就是一个事件循环。我们从 `asyncio` 模块中直接获取一个 `EventLoop` 的引用，然后把需要执行的协程扔到 `EventLoop` 中执行，就实现了异步IO
- `@asyncio.coroutine` 把一个生成器标记为 coroutine 类型，然后，我们就把这个 `coroutine` 扔到 `EventLoop` 中执行
- 运行流程如下：
  - 创建 asyncio 事件循环（此时控制权仍在主线程 main 里）
  - `loop.run_until_complete(supervisor())` 启动这个协程直到它完成才返回，运行到这里后，控制权就转移了出去，转移给了这个事件循环，由它来调度内部的事件。
  - 此时只有一个事件（协程）：supervisor
  - supervisor 协程调用 `spinner = asyncio.ensure_future(spin('thinking!'))` ，这样就又将一个事件（协程）扔进了事件循环中，这样，事件循环就有了两个事件，此时正在执行 supervisor
  - `result = yield from slow_function()`：这里，这个 supervisor 协程，又启动了一个新的协程 slow_function，并且将自己的控制权交给了它
  - 此时，一共有 3 个协程了，并且此时进入了 slow_function 协程
  - `yield from asyncio.sleep(3)` ，slow_function 协程直接将控制权交出去，交给了 spin 协程和 supervisor 协程
  - supervisor 要一直等待 slow_function 协程完成，因此实际只有 spin 协程在执行
  - spin 协程每 0.1 秒将自己的控制权交出去一次，直到 3 秒后，slow_function 终于可以获取线程资源
  - slow_function 协程完成，于是 supervisor 协程获取到线程资源
  - supervisor 通知 spin 协程取消
  - spin 协程于是就收到了 CancelledError 于是最终完成。\





## async/await 方式（推荐）

python 3.5 之后应该使用 async/await 方式来使用协程，基本操作就是将上面 @asyncio.coroutine 注解的函数替换为 `async def` 定义的函数，将 `yield from` 替换为 `await`

```
import asyncio
import itertools
import sys


async def spin(msg):
    write, flush = sys.stdout.write, sys.stdout.flush
    status = ''
    for char in itertools.cycle('|/-\\'):
        status = char + ' ' + msg
        write(status)
        flush()
        write('\x08' * len(status))
        try:
            await asyncio.sleep(.1)  # 睡 0.1 秒，实际来说是将线程的控制权交出去，线程还是会继续执行其它的代码（协程）
        except asyncio.CancelledError:
            break  # 这里表示被其它协程将自己这个协程给取消了，相当于一种通知机制
    write(' ' * len(status) + '\x08' * len(status))


async def slow_function():
    # 假装等待I/O一段时间
    await asyncio.sleep(3)  # 这个协程休眠 3 秒钟，同样的，执行这个协程的线程去执行其它协程了
    return 42


async def supervisor():
    spinner = asyncio.ensure_future(spin('thinking!'))  # 将这个协程丢进 event loop，然后返回一个 future
    print('spinner object:', spinner)
    result = await slow_function()  # 本协程将控制权交出去，交给这个 slow function
    spinner.cancel()  # 运行到这里的时候，spin 已经运行过一段时间了
    return result


def main():
    loop = asyncio.get_event_loop()
    result = loop.run_until_complete(supervisor())
    loop.close()
    print('Answer:', result)


if __name__ == '__main__':
    main()

```

- 开启事件循环
- 事件循环里丢入一个起始的事件（就像 node 里的主模块一样）
- 起始事件不停的提交新的事件到事件循环
- 等待这个起始事件完成后从事件循环里返回：
  - 此时事件循环里可能还有其他 “正在执行” 的事件，实际来说，他们的执行状态被冻结了
  - 关闭事件循环后，这些事件将会被一并关闭
  - 也就是说并不是和 node 一样会等待所有事件完成，而是只等待这一个事件完成，而这一个事件可能会依赖其他事件，就也会一并完成



